#!/bin/bash

echo "Starting Convert"

src_file=$1
dest_file="${src_file/.wav/.mp3}"

echo "Converting $src_file to $dest_file"

ffmpeg -v 0 -i "$src_file" -acodec libmp3lame -b:a 320k "$dest_file" > /dev/null
